apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-connector
  namespace: name-namespace
  labels:
    app: db-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-connector
  template:
    metadata:
      labels:
        app: db-connector
    spec:
      containers:
      - name: db-connector
        image: hasura/graphql-data-connector:v2.43.0  # Image yang digunakan
        ports:
        - containerPort: 8080  # Port dalam container tempat aplikasi berjalan
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: "postgres://<db_user>:<db_password>@<db_host>:<db_port>/<db_name>"  # PostgreSQL connection string
        - name: HASURA_GRAPHQL_DATABASE_URL_MYSQL
          value: "mysql://<db_user>:<db_password>@<db_host>:<db_port>/<db_name>"  # MySQL connection string
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"  # Mengaktifkan Hasura Console
        - name: HASURA_GRAPHQL_DEV_MODE
          value: "true"
        - name: HASURA_GRAPHQL_LOG_LEVEL
          value: "info"  # Level log, bisa diatur ke debug untuk troubleshooting
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
